aws_profile         = "mesa_dev" # your AWS profile (under ~/.aws/credentials) 
company             = "brt" # your company name
region              = "" # e.g. eu-central-1
# vpc_cidr            = "" # default: 10.0.0.0/16
vpc_ipam            = true
vpc_ipam_pool_id     = "ipam-pool-0aa8c1f27a9b2021e"
ec2_key             = "" # path to your .pub key
queue_address       = ""
valohai_assume_user = ""
